title: Wang Jingyi 王竟亦
url: "wang-jingyi.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "wang-jingyi.github.io"
footer_text: "To a great mind, nothing is little."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 # - name: "Resume"
 #   link: "main.pdf"
 - name: "Publications"
   link: "pubs"
